const addressArray = [
    "Dãy nhà D, Khu tập thể Di Dân Vĩnh Phúc 7,2 Ha, Phường Vĩnh Phúc, Quận Ba Đình",
    "Dãy nhà D2, Khu tập thể Giảng Võ, Phường Giảng Võ, Quận Ba Đình",
    "Số 1, Phố Trấn Vũ, Phường Trúc Bạch, Quận Ba Đình",
    "Số 14, Phố Láng Hạ, Phường Thành Công, Quận Ba Đình",
    "Số 170, Phố Ngọc Khánh, Phường Ngọc Khánh, Quận Ba Đình",
    "Số 175, Phố Nguyễn Thái Học, Phường Điện Biên, Quận Ba Đình",
    "Số 175, Phố Nguyễn Thái Học, Phường Điện Biên, Quận Ba Đình",
    "Số 175, Phố Nguyễn Thái Học, Phường Điện Biên, Quận Ba Đình",
    "Số 175, Phố Nguyễn Thái Học, Phường Điện Biên, Quận Ba Đình",
    "Số 218, Phố Đội Cấn, Phường Cống Vị, Quận Ba Đình",
    "Số 248, Phố Kim Mã, Phường Kim Mã, Quận Ba Đình",
    "Số 34, Phố Trần Phú, Phường Điện Biên, Quận Ba Đình",
    "Số 38, Phố Phan Đình Phùng, Phường Quán Thánh, Quận Ba Đình",
    "Số 49, Phố Nguyễn Thái Học, Phường Điện Biên, Quận Ba Đình",
    "Số 526, Phố Đội Cấn, Phường Cống Vị, Quận Ba Đình",
    "Số 57, Phố Nghĩa Dũng, Phường Phúc Xá, Quận Ba Đình",
    "Số 6, Phố Đào Tấn, Phường Cống Vị, Quận Ba Đình",
    "Số 68, Phố Ngọc Hà, Phường Ngọc Hà, Quận Ba Đình",
    "Số 76, Ngõ 84, Phố Ngọc Khánh, Phường Giảng Võ, Quận Ba Đình",
    "Số 8, Phố Quán Thánh, Phường Nguyễn Trung Trực, Quận Ba Đình",
    "Số 1, Đường Tân Xuân, Phường Xuân Đỉnh, Quận Bắc Từ Liêm",
    "Số 1, Đường Tân Xuân, Phường Xuân Đỉnh, Quận Bắc Từ Liêm",
    "Số 10, Đường Phố Nhổn, Phường Tây Tựu, Quận Bắc Từ Liêm",
    "Số 101, Dãy nhà CT1, Khu tập thể Xuân Đỉnh, Phường Xuân Đỉnh, Quận Bắc Từ Liêm",
    "Số 26, Đường Phạm Văn Đồng, Phường Xuân Đỉnh, Quận Bắc Từ Liêm",
    "Đường Hồ Tùng Mậu, Phường Mai Dịch, Quận Cầu Giấy",
    "Đường Nguyễn Phong Sắc, Phường Nghĩa Tân, Quận Cầu Giấy",
    "Đường Phạm Hùng, Phường Trung Hòa, Quận Cầu Giấy",
    "Đường Phạm Hùng, Phường Trung Hòa, Quận Cầu Giấy",
    "Đường Trung Yên 3, Phường Trung Hòa, Quận Cầu Giấy",
    "Số 01, Đường Trung Kính, Phường Trung Hòa, Quận Cầu Giấy",
    "Số 1, Đường Trung Kính, Phường Trung Hòa, Quận Cầu Giấy",
    "Số 1, Đường Trung Kính, Phường Trung Hòa, Quận Cầu Giấy",
    "Số 10, Phố Hoàng Sâm, Phường Nghĩa Đô, Quận Cầu Giấy",
    "Số 136, Đường Xuân Thủy, Phường Dịch Vọng Hậu, Quận Cầu Giấy",
    "Số 165, Đường Cầu Giấy, Phường Quan Hoa, Quận Cầu Giấy",
    "Số 165, Đường Cầu Giấy, Phường Quan Hoa, Quận Cầu Giấy",
    "Số 393, Đường Hoàng Quốc Việt, Phường Nghĩa Tân, Quận Cầu Giấy",
    "Số 5, Đường Nguyễn Khánh Toàn, Phường Dịch Vọng, Quận Cầu Giấy",
    "Số P100, Dãy nhà A15, Khu tập thể Nghĩa Tân, Phường Nghĩa Tân, Quận Cầu Giấy",
    "Dãy nhà B15, Khu tập thể Kim Liên, Phường Kim Liên, Quận Đống Đa",
    "Số 1, Phố Phương Mai, Phường Phương Mai, Quận Đống Đa",
    "Số 1, Phố Tôn Thất Tùng, Phường Trung Tự, Quận Đống Đa",
    "Số 158, Phố Tôn Đức Thắng, Phường Quốc Tử Giám, Quận Đống Đa",
    "Số 17, Phố Đặng Tiến Đông, Phường Trung Liệt, Quận Đống Đa",
    "Số 17, Phố Đặng Tiến Đông, Phường Trung Liệt, Quận Đống Đa",
    "Số 172, Đường Láng, Phường Thịnh Quang, Quận Đống Đa",
    "Số 172, Đường Láng, Phường Thịnh Quang, Quận Đống Đa",
    "Số 172, Đường Láng, Phường Thịnh Quang, Quận Đống Đa",
    "Số 19, Phố Cát Linh, Phường Cát Linh, Quận Đống Đa",
    "Số 305, Phố Tây Sơn, Phường Ngã Tư Sở, Quận Đống Đa",
    "Số 34, Phố Trần Quý Cáp, Phường Văn Miếu, Quận Đống Đa",
    "Số 35, Phố Thái Thịnh, Phường Thịnh Quang, Quận Đống Đa",
    "Số 360/40, Phố Nam Đồng, Phường Nam Đồng, Quận Đống Đa",
    "Số 47, Phố Đặng Tiến Đông, Phường Trung Liệt, Quận Đống Đa",
    "Số 9, Phố Hoàng Cầu, Phường Ô Chợ Dừa, Quận Đống Đa",
    "Số 95, Phố Nguyễn Chí Thanh, Phường Láng Hạ, Quận Đống Đa",
    "Đường Phùng Hưng, Phường Phúc La, Quận Hà Đông",
    "Khối 2, Phường Hà Cầu, Quận Hà Đông",
    "Khối Chiến Thắng, Phường Vạn Phúc, Quận Hà Đông",
    "Khối phố 1, Phường La Khê, Quận Hà Đông",
    "Phố Văn Phú, Phường Phú La, Quận Hà Đông",
    "Phố Xốm, Phường Phú Lãm, Quận Hà Đông",
    "Số 105, Phố Trần Phú, Phường Văn Quán, Quận Hà Đông",
    "Số 4, Đường Quang Trung ( 0 Số ), Phường Yết Kiêu, Quận Hà Đông",
    "Số 4, Đường Quang Trung ( 0 Số ), Phường Yết Kiêu, Quận Hà Đông",
    "Số 4, Đường Quang Trung ( 0 Số ), Phường Yết Kiêu, Quận Hà Đông",
    "Số 4, Đường Quang Trung, Phường Quang Trung, Quận Hà Đông",
    "Số 85, Phố Lê Lợi, Phường Nguyễn Trãi, Quận Hà Đông",
    "Số 94, Phố Trần Phú, Phường Mỗ Lao, Quận Hà Đông",
    "Số No09, Đường Lê Văn Lương kéo dài, Phường La Khê, Quận Hà Đông",
    "Tổ dân phố 1 – Cổ Bản, Phường Đồng Mai, Quận Hà Đông",
    "Tổ dân phố Hoàng Văn Thụ, Phường Dương Nội, Quận Hà Đông",
    "Tổ dân phố số 10 – Yên Lộ, Phường Yên Nghĩa, Quận Hà Đông",
    "Tổ dân phố số 10 Trinh Lương, Phường Phú Lương, Quận Hà Đông",
    "Tổ dân phố số 12, Phường Văn Quán, Quận Hà Đông",
    "Tổ dân phố số 8, Phường Kiến Hưng, Quận Hà Đông",
    "Tổ dân phố số 9, Phường Kiến Hưng, Quận Hà Đông",
    "Tổ dân phố số 9, Phường Phú Lãm, Quận Hà Đông",
    "Tổ dân phố Yên Phúc, Phường Biên Giang, Quận Hà Đông",
    "Dãy nhà N8, Khu tập thể Nguyễn Công Trứ, Phường Phố Huế, Quận Hai Bà Trưng",
    "Số 1, Phố Minh Khai, Phường Trương Định, Quận Hai Bà Trưng",
    "Số 114, Phố Lò Đúc, Phường Đống Mác, Quận Hai Bà Trưng",
    "Số 18, Phố Nguyễn Du, Phường Bùi Thị Xuân, Quận Hai Bà Trưng",
    "Số 187, Phố Trần Đại Nghĩa, Phường Đồng Tâm, Quận Hai Bà Trưng",
    "Số 2, Phố Vân Hồ 3, Phường Lê Đại Hành, Quận Hai Bà Trưng",
    "Số 227, Phố Kim Ngưu, Phường Thanh Lương, Quận Hai Bà Trưng",
    "Số 27B1, Khu B1đầm Trấu, Phường Bạch Đằng, Quận Hai Bà Trưng",
    "Số 48, Phố Thanh Nhàn, Phường Thanh Nhàn, Quận Hai Bà Trưng",
    "Số 68, Phố Trần Nhân Tông, Phường Nguyễn Du, Quận Hai Bà Trưng",
    "Số 69, Phố Lạc Trung, Phường Vĩnh Tuy, Quận Hai Bà Trưng",
    "Số 86B, Phố Võ Thị Sáu, Phường Thanh Nhàn, Quận Hai Bà Trưng",
    "Số 936, Phố Bạch Đằng, Phường Thanh Lương, Quận Hai Bà Trưng",
    "Số P12-A17, Phố Tạ Quang Bửu, Phường Bách Khoa, Quận Hai Bà Trưng",
    "Đường Phúc Tân, Phường Phúc Tân, Quận Hoàn Kiếm",
    "Đường Phúc Tân, Phường Phúc Tân, Quận Hoàn Kiếm",
    "Phố Đinh Lễ, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Phố Hàng Vải, Phường Hàng Bồ, Quận Hoàn Kiếm",
    "Số 1, Phố Hàng Đào, Phường Hàng Đào, Quận Hoàn Kiếm",
    "Số 101, Phố Hàng Bạc, Phường Hàng Bạc, Quận Hoàn Kiếm",
    "Số 118, Phố Lê Duẩn, Phường Cửa Nam, Quận Hoàn Kiếm",
    "Số 14, Phố Trần Hưng Đạo, Phường Phan Chu Trinh, Quận Hoàn Kiếm",
    "Số 14, Phố Trần Hưng Đạo, Phường Phan Chu Trinh, Quận Hoàn Kiếm",
    "Số 15, Phố Đinh Lễ, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 160, Phố Trần Quang Khải, Phường Lý Thái Tổ, Quận Hoàn Kiếm",
    "Số 17, Phố Đinh Lễ, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 18, Phố Đồng Xuân, Phường Đồng Xuân, Quận Hoàn Kiếm",
    "Số 22, Phố Cửa Nam, Phường Cửa Nam, Quận Hoàn Kiếm",
    "Số 22, Phố Tràng Tiền, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 22, Phố Tràng Tiền, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 28, Phố Mã Mây, Phường Hàng Buồm, Quận Hoàn Kiếm",
    "Số 31, Phố Tràng Thi, Phường Hàng Trống, Quận Hoàn Kiếm",
    "Số 4, Phố Lê Văn Linh, Phường Hàng Mã, Quận Hoàn Kiếm",
    "Số 4, Phố Nguyễn Chế Nghĩa, Phường Hàng Bài, Quận Hoàn Kiếm",
    "Số 49, Phố Hai Bà Trưng, Phường Trần Hưng Đạo, Quận Hoàn Kiếm",
    "Số 6, Phố Đặng Thái Thân, Phường Phan Chu Trinh, Quận Hoàn Kiếm",
    "Số 6, Phố Đinh Lễ, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 66, Phố Lương Văn Can, Phường Hàng Trống, Quận Hoàn Kiếm",
    "Số 66, Phố Tràng Tiền, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 75, Phố Đinh Tiên Hoàng, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 75, Phố Đinh Tiên Hoàng, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 75b, Phố Đinh Tiên Hoàng, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 75b, Phố Đinh Tiên Hoàng, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 75b, Phố Đinh Tiên Hoàng, Phường Tràng Tiền, Quận Hoàn Kiếm",
    "Số 78, Đường Bạch Đằng, Phường Chương Dương Độ, Quận Hoàn Kiếm",
    "Dãy nhà A, Khu chung cư Định Công, Phường Định Công, Quận Hoàng Mai",
    "Dãy nhà A, Khu chung cư Định Công, Phường Định Công, Quận Hoàng Mai",
    "Đường Lĩnh Nam, Phường Lĩnh Nam, Quận Hoàng Mai",
    "Đường Lĩnh Nam, Phường Lĩnh Nam, Quận Hoàng Mai",
    "Khu Đô Thị Bắc Linh Đàm, Phường Đại Kim, Quận Hoàng Mai",
    "Phố Nguyễn Hữu Thọ, Phường Đại Kim, Quận Hoàng Mai",
    "Số 22A, Ngõ 319, Phố Tam Trinh, Phường Hoàng Văn Thụ, Quận Hoàng Mai",
    "Số 25/28, Phố Tam Trinh, Phường Hoàng Văn Thụ, Quận Hoàng Mai",
    "Số 811, Đường Giải Phóng, Phường Giáp Bát, Quận Hoàng Mai",
    "Số lô 14, Khu Đô Thị Định Công – Đại Kim, Phường Đại Kim, Quận Hoàng Mai",
    "Sô´12, Phố Nguyễn An Ninh, Phường Tương Mai, Quận Hoàng Mai",
    "Thôn Tứ Kỳ, Phường Hoàng Liệt, Quận Hoàng Mai",
    "Thôn Vĩnh Thuận, Phường Thanh Trì, Quận Hoàng Mai",
    "Thôn Yên Duyên, Phường Yên Sở, Quận Hoàng Mai",
    "Tổ 21, Phường Thịnh Liệt, Quận Hoàng Mai",
    "Xóm 5, Phường Trần Phú, Quận Hoàng Mai",
    "Xóm 9, Phường Lĩnh Nam, Quận Hoàng Mai",
    "Đường Nguyễn Văn Linh, Phường Sài Đồng, Quận Long Biên",
    "Số 147, Đường Ngô Gia Tự, Phường Đức Giang, Quận Long Biên",
    "Số 147, Đường Ngô Gia Tự, Phường Đức Giang, Quận Long Biên",
    "Số 147, Đường Ngô Gia Tự, Phường Đức Giang, Quận Long Biên",
    "Số 158, Ngõ 158, Phố Nguyễn Văn Cừ, Phường Bồ Đề, Quận Long Biên",
    "Số 23, Ngõ 390, Đường Nguyễn Văn cừ, Phường Bồ Đề, Quận Long Biên",
    "Số 366, Phố Ngọc Lâm, Phường Ngọc Lâm, Quận Long Biên",
    "Số 79, Đường Ngô Gia Tự, Phường Đức Giang, Quận Long Biên",
    "Số Tổ 13 Trạm, Tổ 13, Phường Long Biên, Quận Long Biên",
    "Tổ 1, Phường Giang Biên, Quận Long Biên",
    "Tổ 1, Phường Phúc Lợi, Quận Long Biên",
    "Tổ 10, Phường Cự Khối, Quận Long Biên",
    "Tổ 10, Phường Thượng Thanh, Quận Long Biên",
    "Tổ 6, Phường Thạch Bàn, Quận Long Biên",
    "Đường Cổ Nhuế, Xã Cổ Nhuế, Quận Nam Từ Liêm",
    "Đường Hồ Tùng Mậu, Phường Cầu Diễn, Quận Nam Từ Liêm",
    "Đường Nguyễn Cơ Thạch, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Đường Tân Xuân, Xã Xuân Đỉnh, Quận Nam Từ Liêm",
    "Khu phố Lô A2/CN8 cụm công nghiệp vừa và n, Phường Phương Canh, Quận Nam Từ Liêm",
    "Số 14, Đường Nguyễn Cơ Thạch, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 14, Đường Nguyễn Cơ Thạch, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 171, Đường Xuân Phương, Phường Phương Canh, Quận Nam Từ Liêm",
    "Số 19, Đường Nguyễn Cơ Thạch, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 19, Đường Nguyễn Cơ Thạch, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 26, Đường Phạm Văn Đồng, Xã Xuân Đỉnh, Quận Nam Từ Liêm",
    "Số 26, Đường Phạm Văn Đồng, Xã Xuân Đỉnh, Quận Nam Từ Liêm",
    "Số 5, Đường Mỹ Đình, ngõ 322, ngách 322/158, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Xã Mỹ Đình, Quận Nam Từ Liêm",
    "Số 5, Đường Phạm Hùng, Xã Mỹ Đình, Quận Nam Từ Liêm",
    "Số 522, Tổ dân phố xóm Tháp, Phường Đại Mỗ, Quận Nam Từ Liêm",
    "Thôn Đông Ba, Xã Thượng Cát, Quận Nam Từ Liêm",
    "Thôn Đông Sen, Xã Thụy Phương, Quận Nam Từ Liêm",
    "Thôn Đông, Xã Xuân Đỉnh, Quận Nam Từ Liêm",
    "Thôn Ngoạ Long, Xã Minh Khai, Quận Nam Từ Liêm",
    "Thôn Nhân Mỹ, Xã Mỹ Đình, Quận Nam Từ Liêm",
    "Thôn Thị Cẩm, Phường Xuân Phương, Quận Nam Từ Liêm",
    "Thôn Trung Văn, Phường Trung Văn, Quận Nam Từ Liêm",
    "Thôn Văn Trì, Xã Minh Khai, Quận Nam Từ Liêm",
    "Thôn Viên 1, Xã Cổ Nhuế, Quận Nam Từ Liêm",
    "Tổ dân phố xóm Tháp, Phường Đại Mỗ, Quận Nam Từ Liêm",
    "Xóm 3, Xã Đông Ngạc, Quận Nam Từ Liêm",
    "Xóm 6, Xã Đông Ngạc, Quận Nam Từ Liêm",
    "Xóm Cổng Cầu, Xã Liên Mạc, Quận Nam Từ Liêm",
    "Đường Nguyễn Hoàng Tôn, Phường Xuân La, Quận Tây Hồ",
    "Số 16A, Phố Yên Phụ, Phường Yên Phụ, Quận Tây Hồ",
    "Số 397, Đường Âu Cơ, Phường Nhật Tân, Quận Tây Hồ",
    "Số 552, Phố Thụy Khuê, Phường Bưởi, Quận Tây Hồ",
    "Số 642, Đường Lạc Long Quân, Phường Nhật Tân, Quận Tây Hồ",
    "Số 675, Phố Vệ Hồ, Phường Xuân La, Quận Tây Hồ",
    "Dãy nhà C10, Khu tập thể Thanh Xuân Bắc, Phường Thanh Xuân Bắc, Quận Thanh Xuân",
    "Số 148, Phố Bùi Xương Trạch, Phường Khương Đình, Quận Thanh Xuân",
    "Số 16, Ngõ 80, Đường Lê Trọng Tấn, Phường Khương Mai, Quận Thanh Xuân",
    "Số 171, Đường Trường Chinh, Phường Khương Mai, Quận Thanh Xuân",
    "Số 185, Phố Nguyễn Ngọc Nại, Phường Khương Mai, Quận Thanh Xuân",
    "Số 2/40, Phố Phan Đình Giót, Phường Phương Liệt, Quận Thanh Xuân",
    "Số 20, Đường Khương Đình, Phường Thượng Đình, Quận Thanh Xuân",
    "Số 51, Đường Vũ Trọng Phụng, Phường Thanh Xuân Trung, Quận Thanh Xuân",
    "Số 51, Đường Vũ Trọng Phụng, Phường Thanh Xuân Trung, Quận Thanh Xuân",
    "Đường Hữu Nghị, Phường Xuân Khanh, Thị xã Sơn Tây",
    "Khu phố 7, Xã Trung Sơn Trầm, Thị xã Sơn Tây",
    "Số 1, Phố Phùng Khắc Khoan, Phường Quang Trung, Thị xã Sơn Tây",
    "Số 3, Phố Chùa Thông, Phường Sơn Lộc, Thị xã Sơn Tây",
    "Thôn Đông Sàng, Xã Đường Lâm, Thị xã Sơn Tây",
    "Thôn Khoang Sau, Xã Sơn Đông, Thị xã Sơn Tây",
    "Thôn Kim Tân, Xã Kim Sơn, Thị xã Sơn Tây",
    "Thôn Phù Xa, Xã Viên Sơn, Thị xã Sơn Tây",
    "Thôn Trại Hồ, Xã Cổ Đông, Thị xã Sơn Tây",
    "Thôn Triều Đông, Xã Cổ Đông, Thị xã Sơn Tây",
    "Thôn Vân Gia, Xã Trung Hưng, Thị xã Sơn Tây",
    "Thôn Vị Thuỷ, Xã Thanh Mỹ, Thị xã Sơn Tây",
    "Thôn Xuân Khanh ( Đội 6 ), Xã Xuân Sơn, Thị xã Sơn Tây",
    "Đường 32, Thị Trấn Tây Đằng, Huyện Ba Vì",
    "Thôn 2, Xã Minh Châu, Huyện Ba Vì",
    "Thôn 5, Xã Ba Trại, Huyện Ba Vì",
    "Thôn Bặn, Xã Vân Hoà, Huyện Ba Vì",
    "Thôn Bưởi, Xã Khánh Thượng, Huyện Ba Vì",
    "Thôn Cẩm Phương, Xã Tản Lĩnh, Huyện Ba Vì",
    "Thôn Cẩm Tân, Xã Cẩm Lĩnh, Huyện Ba Vì",
    "Thôn Chi Lai, Xã Đồng Thái, Huyện Ba Vì",
    "Thôn Chợ Mơ, Xã Vạn Thắng, Huyện Ba Vì",
    "Thôn Chu Quyến, Xã Chu Minh, Huyện Ba Vì",
    "Thôn Cổ Đô, Xã Cổ Đô, Huyện Ba Vì",
    "Thôn Cốc Thôn, Xã Cam Thượng, Huyện Ba Vì",
    "Thôn Cộng Hoà, Xã Thái Hoà, Huyện Ba Vì",
    "Thôn Đan Thê, Xã Sơn Đà, Huyện Ba Vì",
    "Thôn Đan Thê, Xã Sơn Đà, Huyện Ba Vì",
    "Thôn Đông Phương, Xã Cẩm Lĩnh, Huyện Ba Vì",
    "Thôn Đông Viên, Xã Đồng Quang, Huyện Ba Vì",
    "Thôn Đức Thịnh, Xã Tản Lĩnh, Huyện Ba Vì",
    "Thôn Hạc Sơn, Xã Châu Sơn, Huyện Ba Vì",
    "Thôn Hợp Sơn, Xã Ba Vì, Huyện Ba Vì",
    "Thôn La Thiện, Xã Tản Hồng, Huyện Ba Vì",
    "Thôn Liên Minh, Xã Thụy An, Huyện Ba Vì",
    "Thôn Lương Khê, Xã Thuần Mỹ, Huyện Ba Vì",
    "Thôn Mai Trai, Xã Vạn Thắng, Huyện Ba Vì",
    "Thôn Mộc, Xã Minh Quang, Huyện Ba Vì",
    "Thôn Muỗi, Xã Yên Bài, Huyện Ba Vì",
    "Thôn Phong Vân, Xã Phong Vân, Huyện Ba Vì",
    "Thôn Phú Hữu, Xã Phú Sơn, Huyện Ba Vì",
    "Thôn Phú Nghĩa, Xã Phú Đông, Huyện Ba Vì",
    "Thôn Phú Thịnh, Xã Phú Cường, Huyện Ba Vì",
    "Thôn Phú Xuyên, Xã Phú Châu, Huyện Ba Vì",
    "Thôn Phương Khê, Xã Phú Phương, Huyện Ba Vì",
    "Thôn Sổ, Xã Minh Quang, Huyện Ba Vì",
    "Thôn Thái Bạt, Xã Tòng Bạt, Huyện Ba Vì",
    "Thôn Thanh Lũng, Xã Tiên Phong, Huyện Ba Vì",
    "Thôn Vật Lại, Xã Vật Lại, Huyện Ba Vì",
    "Khu Tân Bình, Thị Trấn Xuân Mai, Huyện Chương Mỹ",
    "Khu Trung Tâm, Xã Đồng Lạc, Huyện Chương Mỹ",
    "Khu Trung Tâm, Xã Đông Sơn, Huyện Chương Mỹ",
    "Khu Trung Tâm, Xã Hữu Văn, Huyện Chương Mỹ",
    "Khu Trung Tâm, Xã Mỹ Lương, Huyện Chương Mỹ",
    "Khu Trung Tâm, Xã Thanh Bình, Huyện Chương Mỹ",
    "Khu Trung Tâm, Xã Trần Phú, Huyện Chương Mỹ",
    "Khu Trung Tâm, Xã Trường Yên, Huyện Chương Mỹ",
    "Phố Chợ Chúc Sơn, Thị Trấn Chúc Sơn, Huyện Chương Mỹ",
    "Phố Miếu Môn, Xã Trần Phú, Huyện Chương Mỹ",
    "Khu Trung Tâm, Xã Đông Phương Yên, Huyện Chương Mỹ",
    "Thôn Xuân Linh, Xã Thủy Xuân Tiên, Huyện Chương Mỹ",
    "Thôn An Thượng, Xã Thượng Vực, Huyện Chương Mỹ",
    "Thôn Cấp Tiến, Xã Văn Võ, Huyện Chương Mỹ",
    "Thôn Chùa Trầm, Xã Phụng Châu, Huyện Chương Mỹ",
    "Thôn Chúc Lý, Xã Ngọc Hoà, Huyện Chương Mỹ",
    "Thôn Cổ Pháp, Xã Tiên Phương, Huyện Chương Mỹ",
    "Thôn Cốc Hạ, Xã Hoàng Diệu, Huyện Chương Mỹ",
    "Thôn Công Am, Xã Hoàng Văn Thụ, Huyện Chương Mỹ",
    "Thôn Đại Từ, Xã Lam Điền, Huyện Chương Mỹ",
    "Thôn Đầm Kênh, Xã Tốt Động, Huyện Chương Mỹ",
    "Thôn Đông Tiến, Xã Tân Tiến, Huyện Chương Mỹ",
    "Thôn Hoàng Xá, Xã Đồng Phú, Huyện Chương Mỹ",
    "Thôn Lưu Xá, Xã Hoà Chính, Huyện Chương Mỹ",
    "Thôn Nam Hài, Xã Nam Phương Tiến, Huyện Chương Mỹ",
    "Thôn Phúc Cầu, Xã Thụy Hương, Huyện Chương Mỹ",
    "Thôn Quan Châm, Xã Phú Nghĩa, Huyện Chương Mỹ",
    "Thôn Quảng Bị 2, Xã Quảng Bị, Huyện Chương Mỹ",
    "Thôn Quảng Bị 5, Xã Quảng Bị, Huyện Chương Mỹ",
    "Thôn Tân Thôn, Xã Phú Nam An, Huyện Chương Mỹ",
    "Thôn Thái Hoà, Xã Hợp Đồng, Huyện Chương Mỹ",
    "Thôn Trung Cao, Xã Trung Hoà, Huyện Chương Mỹ",
    "Thôn Văn Phú, Xã Hoàng Văn Thụ, Huyện Chương Mỹ",
    "Thôn Yên Cốc, Xã Hồng Phong, Huyện Chương Mỹ",
    "Thôn Yên Trường, Xã Trường Yên, Huyện Chương Mỹ",
    "Xóm Yên Khê, Xã Đại Yên, Huyện Chương Mỹ",
    "Đường 32, Thị Trấn Phùng, Huyện Đan Phượng",
    "Đường 32, Thị Trấn Phùng, Huyện Đan Phượng",
    "Thôn ( Cụm Dân Cư Số 3 ), Xã Thọ Xuân, Huyện Đan Phượng",
    "Thôn 7, Xã Trung Châu, Huyện Đan Phượng",
    "Thôn Bá Nội, Xã Hồng Hà, Huyện Đan Phượng",
    "Thôn Bãi Tháp, Xã Đồng Tháp, Huyện Đan Phượng",
    "Thôn Đại Phú, Xã Thượng Mỗ, Huyện Đan Phượng",
    "Thôn Đan Hội, Xã Tân Lập, Huyện Đan Phượng",
    "Thôn Địch Trung, Xã Phương Đình, Huyện Đan Phượng",
    "Thôn Đoài, Xã Liên Hà, Huyện Đan Phượng",
    "Thôn Đông Hải, Xã Thọ An, Huyện Đan Phượng",
    "Thôn Hạ Mỗ, Xã Hạ Mỗ, Huyện Đan Phượng",
    "Thôn Tháp Thượng, Xã Song Phượng, Huyện Đan Phượng",
    "Thôn Thuý Hội, Xã Tân Hội, Huyện Đan Phượng",
    "Thôn Tổ, Xã Liên Hồng, Huyện Đan Phượng",
    "Thôn Trung, Xã Liên Trung, Huyện Đan Phượng",
    "Khu phố Vân Trì, Xã Vân Nội, Huyện Đông Anh",
    "Khu phố Vân Trì, Xã Vân Nội, Huyện Đông Anh",
    "Thôn Bắc, Xã Kim Nỗ, Huyện Đông Anh",
    "Thôn Bầu, Xã Kim Chung, Huyện Đông Anh",
    "Thôn Bầu, Xã Kim Chung, Huyện Đông Anh",
    "Thôn Cổ Điển, Xã Hải Bối, Huyện Đông Anh",
    "Thôn Đại Độ, Xã Võng La, Huyện Đông Anh",
    "Thôn Đại Đồng, Xã Đại Mạch, Huyện Đông Anh",
    "Thôn Đông, Xã Tàm Xá, Huyện Đông Anh",
    "Thôn Đông, Xã Việt Hùng, Huyện Đông Anh",
    "Thôn Hà Khê, Xã Vân Hà, Huyện Đông Anh",
    "Thôn Hà Lâm 3, Xã Thụy Lâm, Huyện Đông Anh",
    "Thôn Hà Lỗ, Xã Liên Hà, Huyện Đông Anh",
    "Thôn Hải Bối, Xã Hải Bối, Huyện Đông Anh",
    "Thôn Khê Nữ, Xã Nguyên Khê, Huyện Đông Anh",
    "Thôn Kính Nỗ, Xã Uy Nỗ, Huyện Đông Anh",
    "Thôn Lại Đà, Xã Đông Hội, Huyện Đông Anh",
    "Thôn Lộc Hà, Xã Mai Lâm, Huyện Đông Anh",
    "Thôn Lực Canh, Xã Xuân Canh, Huyện Đông Anh",
    "Thôn Mai Hiên, Xã Mai Lâm, Huyện Đông Anh",
    "Thôn Phù Liễn, Xã Bắc Hồng, Huyện Đông Anh",
    "Thôn Phương Trạch, Xã Vĩnh Ngọc, Huyện Đông Anh",
    "Thôn Tiên Kha, Xã Tiên Dương, Huyện Đông Anh",
    "Thôn Tiền, Xã Dục Tú, Huyện Đông Anh",
    "Thôn Vệ, Xã Nam Hồng, Huyện Đông Anh",
    "Thôn Xuân Nộn, Xã Xuân Nộn, Huyện Đông Anh",
    "Tổ 13, Thị Trấn Đông Anh, Huyện Đông Anh",
    "Tổ 4, Thị Trấn Đông Anh, Huyện Đông Anh",
    "Xóm Chợ, Xã Cổ Loa, Huyện Đông Anh",
    "Dãy nhà A, Khu dân cư Đê Đa Tốn, Xã Đa Tốn, Huyện Gia Lâm",
    "Đường 79, Xã Dương Xá, Huyện Gia Lâm",
    "Khu Chợ Bún, Xã Đa Tốn, Huyện Gia Lâm",
    "Ngõ 7, Thôn Cống Thôn, Xã Yên Viên, Huyện Gia Lâm",
    "Phố Keo, Xã Kim Sơn, Huyện Gia Lâm",
    "Số 197, Đường Nguyễn Đức Thuận, Thị trấn Trâu Quỳ, Huyện Gia Lâm",
    "Sô´183, Đường Hà Huy Tập, Thị Trấn Yên Viên, Huyện Gia Lâm",
    "Sô´197, Đường Nguyễn Đức Thuận, Thị trấn Trâu Quỳ, Huyện Gia Lâm",
    "Thôn 1, Xã Đình Xuyên, Huyện Gia Lâm",
    "Thôn 1, Xã Ninh Hiệp, Huyện Gia Lâm",
    "Thôn Cam, Xã Cổ Bi, Huyện Gia Lâm",
    "Thôn Chi Nam, Xã Lệ Chi, Huyện Gia Lâm",
    "Thôn Cự Đà, Xã Đặng Xá, Huyện Gia Lâm",
    "Thôn Cự Đà, Xã Đặng Xá, Huyện Gia Lâm",
    "Thôn Đào Nguyễn, Thị trấn Trâu Quỳ, Huyện Gia Lâm",
    "Thôn Phù Dực 1, Xã Phù Đổng, Huyện Gia Lâm",
    "Thôn Sơn Hô, Xã Văn Đức, Huyện Gia Lâm",
    "Thôn Tân Tảo, Xã Phú Thị, Huyện Gia Lâm",
    "Thôn Thượng, Xã Đông Dư, Huyện Gia Lâm",
    "Thôn Thượng, Xã Dương Hà, Huyện Gia Lâm",
    "Thôn Trung Dương, Xã Kiêu Kỵ, Huyện Gia Lâm",
    "Thôn Trung Màu, Xã Trung Mầu, Huyện Gia Lâm",
    "Thôn Yên Mỹ, Xã Dương Quang, Huyện Gia Lâm",
    "Thôn Yên Thường, Xã Yên Thường, Huyện Gia Lâm",
    "Xóm 1 Giang Cao, Xã Bát Tràng, Huyện Gia Lâm",
    "Xóm 2, Xã Kim Lan, Huyện Gia Lâm",
    "Xóm 5, Thôn Giang Cao, Xã Bát Tràng, Huyện Gia Lâm",
    "Xóm Đình, Thôn Trung 1, Xã Dương Hà, Huyện Gia Lâm",
    "Khu 6, Thị Trấn Trạm Trôi, Huyện Hoài Đức",
    "Khu Vực 1, Xã Cát Quế, Huyện Hoài Đức",
    "Thôn 5 ( Kỳ ), Xã Yên Sở, Huyện Hoài Đức",
    "Thôn Cựu Quán, Xã Đức Thượng, Huyện Hoài Đức",
    "Thôn Đông Lao, Xã Đông La, Huyện Hoài Đức",
    "Thôn Kim Hoàng, Xã Vân Canh, Huyện Hoài Đức",
    "Thôn Lưu Xá, Xã Đức Giang, Huyện Hoài Đức",
    "Thôn Minh Hoà, Xã Minh Khai, Huyện Hoài Đức",
    "Thôn Ngãi Cầu, Xã An Khánh, Huyện Hoài Đức",
    "Thôn Ngự Câu, Xã An Thượng, Huyện Hoài Đức",
    "Thôn Phương Quan, Xã Vân Côn, Huyện Hoài Đức",
    "Thôn Phương Viên, Xã Song Phương, Huyện Hoài Đức",
    "Thôn Vân Côn, Xã Vân Côn, Huyện Hoài Đức",
    "Thôn Yên Thái, Xã Tiền Yên, Huyện Hoài Đức",
    "Thôn Yên Vĩnh, Xã Kim Chung, Huyện Hoài Đức",
    "Xóm 4, Xã Lai Yên, Huyện Hoài Đức",
    "Xóm 5, Xã Đắc Sở, Huyện Hoài Đức",
    "Xóm Đa, Xã Di Trạch, Huyện Hoài Đức",
    "Xóm Độc Lập, Xã La Phù, Huyện Hoài Đức",
    "Xóm Quê, Xã Dương Liễu, Huyện Hoài Đức",
    "Xóm Thượng, Xã Sơn Đồng , Huyện Hoài Đức",
    "Lô 46, Lô 1 đến 46, Khu công nghiệp Quang Minh, Thị Trấn Quang Minh, Huyện Mê Linh",
    "Phố Thị trấn Chi Đông, Thị Trấn Chi Đông, Huyện Mê Linh",
    "Thôn 1, Xã Thạch Đà, Huyện Mê Linh",
    "Thôn Bạch Trữ, Xã Tiến Thắng, Huyện Mê Linh",
    "Thôn Bồng Mạc, Xã Liên Mạc, Huyện Mê Linh",
    "Thôn Chu Phan, Xã Chu Phan, Huyện Mê Linh",
    "Thôn Đại Bái, Xã Đại Thịnh, Huyện Mê Linh",
    "Thôn Đức Hậu, Xã Thanh Lâm, Huyện Mê Linh",
    "Thôn Gia Thượng, Thị Trấn Quang Minh, Huyện Mê Linh",
    "Thôn Hạ Lôi, Xã Mê Linh, Huyện Mê Linh",
    "Thôn Hoàng Xá, Xã Hoàng Kim, Huyện Mê Linh",
    "Thôn Phú Mỹ, Xã Tự Lập, Huyện Mê Linh",
    "Thôn Phù Trì, Xã Kim Hoa, Huyện Mê Linh",
    "Thôn Tam Báo, Xã Tam Đồng , Huyện Mê Linh",
    "Thôn Thọ Lão, Xã Tiến Thịnh, Huyện Mê Linh",
    "Thôn Tráng Việt, Xã Tráng Việt , Huyện Mê Linh",
    "Thôn Văn Quán, Xã Văn Khê, Huyện Mê Linh",
    "Thôn Yên Nhân, Xã Tiền Phong, Huyện Mê Linh",
    "Thôn Yên Nội, Xã Vạn Yên, Huyện Mê Linh",
    "Ấp Đông Bình: Đội 5-6, Xã Hùng Tiến, Huyện Mỹ Đức",
    "Thôn Áng Thượng: Đội 5-6, Xã Lê Thanh, Huyện Mỹ Đức",
    "Thôn Bèn, Xã Tuy Lai, Huyện Mỹ Đức",
    "Thôn Đoài: Đội 3-Đội 5, Xã Xuy Xá, Huyện Mỹ Đức",
    "Thôn Đoan Nữ (Đội 4 đến Đội7), Xã An Mỹ, Huyện Mỹ Đức",
    "Thôn Đốc Tín: Đội 3 – Đội 8, Xã Đốc Tín, Huyện Mỹ Đức",
    "Thôn Đồi Dùng: Đội 7, Xã An Phú, Huyện Mỹ Đức",
    "Thôn Đục Khê: Đội 9-Đội 14, Xã Hương Sơn, Huyện Mỹ Đức",
    "Thôn Hạ Sở: Đội 2, Xã Hồng Sơn, Huyện Mỹ Đức",
    "Thôn Hiền Lương: Đội 4, Xã An Tiến, Huyện Mỹ Đức",
    "Thôn Hoành (từ xóm 1A,1B và xóm 2 đến 8), Xã Đồng Tâm, Huyện Mỹ Đức",
    "Thôn Kênh Đào (Đội 2, Đội 3), Xã An Mỹ, Huyện Mỹ Đức",
    "Thôn Kim Bôi (Đội 1đến Đội 10), Xã Vạn Kim, Huyện Mỹ Đức",
    "Thôn La Đồng: Đội 1-Đội 3, Xã Hợp Tiến, Huyện Mỹ Đức",
    "Thôn Lai Tảo: Đội 6 – 10, Xã Bột Xuyên, Huyện Mỹ Đức",
    "Thôn Phúc Lâm: Đội 2-Đội 6, Xã Phúc Lâm, Huyện Mỹ Đức",
    "Thôn Tế Tiêu (Từ Đội 1 đến Đội 4), Thị trấn Đại Nghĩa, Huyện Mỹ Đức",
    "Thôn Tế Tiêu (Từ Đội 1 đến Đội 4), Thị trấn Đại Nghĩa, Huyện Mỹ Đức",
    "Thôn Thượng(từ Đội1-Đội 9), Xã Phùng Xá, Huyện Mỹ Đức",
    "Thôn Trì (từ xóm 1-xóm 2), Xã Thượng Lâm, Huyện Mỹ Đức",
    "Thôn Trinh Tiết: Đội 4 – Đội 8, Xã Đại Hưng, Huyện Mỹ Đức",
    "Thôn Trung: Đội 4-Đội 7, Xã Phù Lưu Tế, Huyện Mỹ Đức",
    "Thôn Vài, Xã Hợp Thanh, Huyện Mỹ Đức",
    "Thôn Viêm Khê: Đội 6-8, Xã Hợp Tiến, Huyện Mỹ Đức",
    "Thôn Vĩnh Lạc: Đội 3-4, Xã Mỹ Thành, Huyện Mỹ Đức",
    "Khu Thị Trấn, Thị Trấn Phú Xuyên, Huyện Phú Xuyên",
    "Thôn Bái Xuyên, Xã Minh Tân , Huyện Phú Xuyên",
    "Thôn Chính, Xã Vân Từ, Huyện Phú Xuyên",
    "Thôn Cổ Trai, Xã Đại Xuyên, Huyện Phú Xuyên",
    "Thôn Đa Chất, Xã Đại Xuyên, Huyện Phú Xuyên",
    "Thôn Đại Nghiệp, Xã Tân Dân, Huyện Phú Xuyên",
    "Thôn Đồng Tiến, Xã Phượng Dực, Huyện Phú Xuyên",
    "Thôn Giẽ Hạ, Xã Phú Yên, Huyện Phú Xuyên",
    "Thôn Hoà Mỹ, Xã Hồng Minh, Huyện Phú Xuyên",
    "Thôn Hoà Thượng, Xã Bạch Hạ, Huyện Phú Xuyên",
    "Thôn Kim Quy, Xã Minh Tân , Huyện Phú Xuyên",
    "Thôn Lập Phương, Xã Khai Thái, Huyện Phú Xuyên",
    "Thôn Lạt Dương, Xã Hồng Thái, Huyện Phú Xuyên",
    "Thôn Nam Phú, Xã Nam Phong, Huyện Phú Xuyên",
    "Thôn Nhị Khê, Xã Hoàng Long, Huyện Phú Xuyên",
    "Thôn Nội, Xã Châu Can, Huyện Phú Xuyên",
    "Thôn Nội, Xã Văn Hoàng, Huyện Phú Xuyên",
    "Thôn Phú Túc, Xã Phú Túc, Huyện Phú Xuyên",
    "Thôn Phúc Lâm, Xã Phúc Tiến, Huyện Phú Xuyên",
    "Thôn Sảo Hạ, Xã Quang Lãng, Huyện Phú Xuyên",
    "Thôn Sơn Thanh, Xã Sơn Hà, Huyện Phú Xuyên",
    "Thôn Tạ Xá, Xã Đại Thắng, Huyện Phú Xuyên",
    "Thôn Thượng, Xã Chuyên Mỹ, Huyện Phú Xuyên",
    "Thôn Thuỵ Phú, Xã Thụy Phú, Huyện Phú Xuyên",
    "Thôn Tranh Thôn, Xã Văn Nhân, Huyện Phú Xuyên",
    "Thôn Tri Thuỷ, Xã Tri Thủy, Huyện Phú Xuyên",
    "Thôn Trung Lập, Xã Tri Trung, Huyện Phú Xuyên",
    "Thôn Văn Lãng, Xã Quang Trung, Huyện Phú Xuyên",
    "Tiểu Khu Phú Thịnh, Thị trấn Phú Minh, Huyện Phú Xuyên",
    "Xóm 12, Xã Nam Triều, Huyện Phú Xuyên",
    "Phố Gạch, Thị Trấn Phúc Thọ, Huyện Phúc Thọ",
    "Thôn Bãi Đồn, Xã Vân Hà, Huyện Phúc Thọ",
    "Thôn Cụm Dân Cư Số 2, Xã Hát Môn, Huyện Phúc Thọ",
    "Thôn Cựu Lục, Xã Xuân Phú, Huyện Phúc Thọ",
    "Thôn Đoài, Xã Tam Hiệp, Huyện Phúc Thọ",
    "Thôn Gia Hoà, Thị Trấn Phúc Thọ, Huyện Phúc Thọ",
    "Thôn Hiệp Lộc, Xã Hiệp Thuận, Huyện Phúc Thọ",
    "Thôn Hiếu Hiệp, Xã Liên Hiệp, Huyện Phúc Thọ",
    "Thôn Hoà Thôn, Xã Tam Hiệp, Huyện Phúc Thọ",
    "Thôn Kim Lũ ( Cụm Dân Cư Số 1 -> Số 2 ), Xã Thượng Cốc, Huyện Phúc Thọ",
    "Thôn Ngọc Tảo, Xã Ngọc Tảo, Huyện Phúc Thọ",
    "Thôn Phú Đa, Xã Thanh Đa, Huyện Phúc Thọ",
    "Thôn Phương Độ, Xã Phương Độ, Huyện Phúc Thọ",
    "Thôn Sen Chiểu, Xã Sen Chiểu, Huyện Phúc Thọ",
    "Thôn Tây, Xã Phụng Thượng , Huyện Phúc Thọ",
    "Thôn Thư Trai, Xã Phúc Hoà, Huyện Phúc Thọ",
    "Thôn Thuần Mỹ, Xã Trạch Mỹ Lộc, Huyện Phúc Thọ",
    "Thôn Triệu Xuyên, Xã Long Xuyên, Huyện Phúc Thọ",
    "Thôn Trung Nam Lộc, Xã Thọ Lộc, Huyện Phúc Thọ",
    "Thôn Trung, Xã Tam Thuấn, Huyện Phúc Thọ",
    "Thôn Tường Phiêu, Xã Tích Giang, Huyện Phúc Thọ",
    "Thôn Vĩnh Lộc, Xã Vân Nam, Huyện Phúc Thọ",
    "Thôn Vĩnh Phúc, Xã Vân Phúc, Huyện Phúc Thọ",
    "Thôn Bảo Lộc, Xã Võng Xuyên, Huyện Phúc Thọ",
    "Thôn Cẩm Đình, Xã Cẩm Đình, Huyện Phúc Thọ",
    "Thôn Ngọc Tảo, Xã Ngọc Tảo, Huyện Phúc Thọ",
    "Thôn Vĩnh Phúc, Xã Vân Phúc, Huyện Phúc Thọ",
    "Đường 21 B Thị Trấn Quốc Oai, Thị Trấn Quốc Oai, Huyện Quốc Oai",
    "Khu 1, Xã Phượng Cách, Huyện Quốc Oai",
    "Thôn Bạch Thạch, Xã Hoà Thạch, Huyện Quốc Oai",
    "Thôn Cấn Thượng, Xã Cấn Hữu, Huyện Quốc Oai",
    "Thôn Cổ Rùa, Xã Phú Mãn, Huyện Quốc Oai",
    "Thôn Đa Phúc, Xã Sài Sơn, Huyện Quốc Oai",
    "Thôn Đại Đồng, Xã Tuyết Nghĩa, Huyện Quốc Oai",
    "Thôn Đại Tảo, Xã Đại Thành, Huyện Quốc Oai",
    "Thôn Đông Hạ, Xã Đông Yên, Huyện Quốc Oai",
    "Thôn Ngọc Phúc, Xã Ngọc Liệp, Huyện Quốc Oai",
    "Thôn Phúc Đức, Xã Sài Sơn, Huyện Quốc Oai",
    "Thôn Sơn Trung, Xã Yên Sơn, Huyện Quốc Oai",
    "Thôn Thái Thượng Khê, Xã Cấn Hữu, Huyện Quốc Oai",
    "Thôn Thế Trụ, Xã Nghĩa Hương, Huyện Quốc Oai",
    "Thôn Yên Nội, Xã Đồng Quang, Huyện Quốc Oai",
    "Thôn Yên Quán, Xã Tân Phú, Huyện Quốc Oai",
    "Thôn 4, Xã Phú Cát, Huyện Quốc Oai",
    "Thôn Bạch Thạch, Xã Hoà Thạch, Huyện Quốc Oai",
    "Thôn Đại Phu, Xã Liệp Tuyết, Huyện Quốc Oai",
    "Thôn Phú Mỹ, Xã Ngọc Mỹ, Huyện Quốc Oai",
    "Thôn Thạch Thán, Xã Thạch Thán, Huyện Quốc Oai",
    "Thôn Thị Nội, Xã Tân Hoà, Huyện Quốc Oai",
    "Xóm Đồng Bèn, Xã Đồng Xuân, Huyện Quốc Oai",
    "Đường Thạch Lỗi, Xã Thanh Xuân, Huyện Sóc Sơn",
    "Khu Đường 2, Xã Phủ Lỗ, Huyện Sóc Sơn",
    "Khu Đường 3, Xã Phù Lỗ, Huyện Sóc Sơn",
    "Khu I Quốc Lộ 2, Xã Phú Minh, Huyện Sóc Sơn",
    "Khu I Quốc Lộ 2, Xã Phú Minh, Huyện Sóc Sơn",
    "Khu I Quốc Lộ 2, Xã Phú Minh, Huyện Sóc Sơn",
    "Khu Núi đôi, Xã Tân Minh, Huyện Sóc Sơn",
    "Khu Sân Bay Nội Bài, Xã Phú Cường, Huyện Sóc Sơn",
    "Khu Thủy Lợi 2, Xã Tân Minh, Huyện Sóc Sơn",
    "Phố Kim Anh, Xã Thanh Xuân, Huyện Sóc Sơn",
    "Phố Nỷ, Xã Trung Giã, Huyện Sóc Sơn",
    "Phố Thá, Xã Xuân Giang, Huyện Sóc Sơn",
    "Sô´1, Khu I Quốc Lộ 2, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Chấu, Xã Bắc Sơn, Huyện Sóc Sơn",
    "Thôn Cộng Hòa, Xã Phù Linh, Huyện Sóc Sơn",
    "Thôn Đông, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Đông, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Đông, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Đông, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Đông, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Đông, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Đông, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Đông, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Đông, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Đức Hậu, Xã Đức Hoà, Huyện Sóc Sơn",
    "Thôn Kinh tế mới Ban Tiện, Xã Minh Phú, Huyện Sóc Sơn",
    "Thôn Lạc Tài, Xã Mai Đình, Huyện Sóc Sơn",
    "Thôn Miếu Thờ, Xã Tiên Dược, Huyện Sóc Sơn",
    "Thôn Nam Cương, Xã Hiền Ninh, Huyện Sóc Sơn",
    "Thôn Ngô Đạo, Xã Tân Hưng, Huyện Sóc Sơn",
    "Thôn Phú Điền, Xã Hồng Kỳ, Huyện Sóc Sơn",
    "Thôn Quán Mỹ, Xã Tân Dân, Huyện Sóc Sơn",
    "Thôn Thái Lai, Xã Minh Trí, Huyện Sóc Sơn",
    "Thôn Thắng Lợi, Xã Phú Minh, Huyện Sóc Sơn",
    "Thôn Thắng Trí, Xã Minh Trí, Huyện Sóc Sơn",
    "Thôn Thanh Thủy, Xã Đông Xuân, Huyện Sóc Sơn",
    "Thôn Thanh Trí, Xã Minh Phú, Huyện Sóc Sơn",
    "Thôn Thanh Vân, Xã Tân Dân, Huyện Sóc Sơn",
    "Thôn Thụy Hương, Xã Phú Cường, Huyện Sóc Sơn",
    "Thôn Tiên Tảo, Xã Việt Long, Huyện Sóc Sơn",
    "Thôn Xuân Bách, Xã Quang Tiến, Huyện Sóc Sơn",
    "Thôn Xuân Dương, Xã Kim Lũ, Huyện Sóc Sơn",
    "Thôn Xuân Lai, Xã Xuân Thu, Huyện Sóc Sơn",
    "Thôn Yên Tàng, Xã Bắc Phú, Huyện Sóc Sơn",
    "Tổ 1, Khu A, Thị Trấn Sóc Sơn, Huyện Sóc Sơn",
    "Tổ 8, Khu C, Thị Trấn Sóc Sơn, Huyện Sóc Sơn",
    "Tổ 8, Khu C, Thị Trấn Sóc Sơn, Huyện Sóc Sơn",
    "Tổ 8, Khu C, Thị Trấn Sóc Sơn, Huyện Sóc Sơn",
    "Xóm Thanh Hoa, Xã Nam Sơn, Huyện Sóc Sơn",
    "Đường 80, Thị Trấn Liên Quan, Huyện Thạch Thất",
    "Khu Trung Tâm Xã ( Làngphú Lễ , Làng Đông Thượng , Xóm Cộng ), Xã Cần Kiệm, Huyện Thạch Thất",
    "Làng Yên ( Thôn 4 -> Thôn 9 ), Xã Thạch Xá, Huyện Thạch Thất",
    "Thôn 2, Xã Chàng Sơn, Huyện Thạch Thất",
    "Thôn 4, Xã Canh Nậu, Huyện Thạch Thất",
    "Thôn 5, Xã Hạ Bằng, Huyện Thạch Thất",
    "Thôn 7, Xã Thạch Hoà, Huyện Thạch Thất",
    "Thôn 9, Xã Hương Ngải, Huyện Thạch Thất",
    "Thôn Bùng, Xã Phùng Xá, Huyện Thạch Thất",
    "Thôn Chi Quan 2, Thị Trấn Liên Quan, Huyện Thạch Thất",
    "Thôn Chiến Thắng, Xã Đồng Trúc, Huyện Thạch Thất",
    "Thôn Cừ Viên, Xã Tân Xã, Huyện Thạch Thất",
    "Thôn Hàn Chùa, Xã Đại Đồng , Huyện Thạch Thất",
    "Thôn Hoà Bình, Xã Dị Nậu, Huyện Thạch Thất",
    "Thôn Hoà Lạc, Xã Bình Yên, Huyện Thạch Thất",
    "Thôn Lại Thượng, Xã Lại Thượng , Huyện Thạch Thất",
    "Thôn Làng Sen Trì, Xã Bình Yên, Huyện Thạch Thất",
    "Thôn Phú Nghĩa, Xã Phú Kim, Huyện Thạch Thất",
    "Thôn Thái Hoà, Xã Bình Phú, Huyện Thạch Thất",
    "Thôn Yên Lỗ, Xã Cẩm Yên, Huyện Thạch Thất",
    "Xóm Đình Chùa, Xã Hữu Bằng, Huyện Thạch Thất",
    "Xóm Giáp Tây Chùa, Xã Kim Quan, Huyện Thạch Thất",
    "Xóm Đình, Xã Yên Bình, Huyện Thạch Thất",
    "Xóm Gò Chòi A, Xã Tiến Xuân, Huyện Thạch Thất",
    "Xóm Lụa, Xã Yên Bình, Huyện Thạch Thất",
    "Xóm Sổ, Xã Yên Trung, Huyện Thạch Thất",
    "Khu Nội Thị, Thị Trấn Kim Bài, Huyện Thanh Oai",
    "Khu Trung Tâm Xã, Xã Bích Hoà, Huyện Thanh Oai",
    "Khu Trung Tâm Xã, Xã Mỹ Hương, Huyện Thanh Oai",
    "Khu Trung Tâm, Xã Tam Hưng, Huyện Thanh Oai",
    "Phố Vác, Xã Dân Hoà, Huyện Thanh Oai",
    "Thôn Bạch Nao, Xã Thanh Văn, Huyện Thanh Oai",
    "Thôn Bình Đà 1, Xã Bình Minh, Huyện Thanh Oai",
    "Thôn Bình Đà 1, Xã Bình Minh, Huyện Thanh Oai",
    "Thôn Đôn Thư, Xã Kim Thư, Huyện Thanh Oai",
    "Thôn Gia Vĩnh, Xã Thanh Thùy, Huyện Thanh Oai",
    "Thôn Khê Tang, Xã Cự Khê, Huyện Thanh Oai",
    "Thôn Mã Kiều, Xã Phương Trung, Huyện Thanh Oai",
    "Thôn Mai Châu, Xã Liên Châu, Huyện Thanh Oai",
    "Thôn Ngọc Liên, Xã Kim An, Huyện Thanh Oai",
    "Thôn Phúc Thuỵ, Xã Tân Ước, Huyện Thanh Oai",
    "Thôn Tảo Dương, Xã Hồng Dương, Huyện Thanh Oai",
    "Thôn Văn Quán, Xã Đỗ Động, Huyện Thanh Oai",
    "Thôn Vỹ, Xã Cao Viên, Huyện Thanh Oai",
    "Thôn Xuyên Dương, Xã Xuân Dương, Huyện Thanh Oai",
    "Thôn Gia Vĩnh, Xã Thanh Thùy, Huyện Thanh Oai",
    "Thôn Mộc Xá, Xã Cao Dương, Huyện Thanh Oai",
    "Thôn My Thượng, Xã Thanh Mai, Huyện Thanh Oai",
    "Thôn Thanh Hiền, Xã Thanh Cao, Huyện Thanh Oai",
    "Số 7, ngõ 405, Tổ 11, Khu Ga, Thị trấn Văn Điển, Huyện Thanh Trì",
    "Đội 9, Thôn Thanh Oai, Xã Hữu Hoà, Huyện Thanh Trì",
    "Thôn 1, Xã Đông Mỹ, Huyện Thanh Trì",
    "Thôn 2, Xã Đông Mỹ, Huyện Thanh Trì",
    "Thôn 2, Xã Vạn Phúc, Huyện Thanh Trì",
    "Thôn Đại Áng, Xã Đại Áng, Huyện Thanh Trì",
    "Thôn Huỳnh Cung, Xã Tam Hiệp, Huyện Thanh Trì",
    "Thôn Nhân Hoà, Xã Tả Thanh Oai, Huyện Thanh Trì",
    "Thôn Phương Nhị, Xã Liên Ninh, Huyện Thanh Trì",
    "Thôn Tự Khoát, Xã Ngũ Hiệp, Huyện Thanh Trì",
    "Thôn Văn Uyên, Xã Duyên Hà, Huyện Thanh Trì",
    "Thôn Vĩnh Ninh, Xã Vĩnh Quỳnh, Huyện Thanh Trì",
    "Tổ 11, Khu Ga, Thị trấn Văn Điển, Huyện Thanh Trì",
    "Xóm 7, Xã Yên Mỹ, Huyện Thanh Trì",
    "Xóm Cầu, Xã Thanh Liệt, Huyện Thanh Trì",
    "Xóm Chùa, Xã Tân Triều, Huyện Thanh Trì",
    "Khối Thị Trấn, Thị Trấn Thường Tín, Huyện Thường Tín",
    "Khối Thị Trấn, Thị Trấn Thường Tín, Huyện Thường Tín",
    "Thôn Ba Lăng, Xã Dũng Tiến, Huyện Thường Tín",
    "Thôn Bạch Liên, Xã Liên Phương, Huyện Thường Tín",
    "Thôn Bằng Sở, Xã Ninh Sở, Huyện Thường Tín",
    "Thôn Chương Dương, Xã Chương Dương, Huyện Thường Tín",
    "Thôn Đinh Xá, Xã Văn Tự, Huyện Thường Tín",
    "Thôn Đỗ Hà, Xã Khánh Hà, Huyện Thường Tín",
    "Thôn Đô Quan, Xã Quất Động, Huyện Thường Tín",
    "Thôn Đống Tranh, Xã Minh Cường, Huyện Thường Tín",
    "Thôn Hạ Thái, Xã Duyên Thái, Huyện Thường Tín",
    "Thôn Lau Yên, Xã Tân Minh, Huyện Thường Tín",
    "Thôn Mai Sao, Xã Nguyễn Trãi, Huyện Thường Tín",
    "Thôn Nghiêm Xá, Xã Nghiêm Xuyên, Huyện Thường Tín",
    "Thôn Nhân Hiền, Xã Hiền Giang, Huyện Thường Tín",
    "Thôn Quần Hiền, Xã Hoà Bình, Huyện Thường Tín",
    "Thôn Thư Dương, Xã Thư Phú, Huyện Thường Tín",
    "Thôn Thượng Đình, Xã Nhị Khê, Huyện Thường Tín",
    "Thôn Thượng Giáp, Xã Thống Nhất, Huyện Thường Tín",
    "Thôn Trát Cầu, Xã Tiền Phong, Huyện Thường Tín",
    "Thôn Tử Dương, Xã Tô Hiệu, Huyện Thường Tín",
    "Thôn Từ Vân, Xã Lê Lợi, Huyện Thường Tín",
    "Thôn Vạn Điểm, Xã Vạn Điểm, Huyện Thường Tín",
    "Thôn Vân Hoà, Xã Vân Tảo, Huyện Thường Tín",
    "Thôn Văn Hội, Xã Văn Bình, Huyện Thường Tín",
    "Thôn Vân La, Xã Hồng Vân, Huyện Thường Tín",
    "Thôn Văn Xá, Xã Nhị Khê, Huyện Thường Tín",
    "Thôn Yên Phú, Xã Văn Phú, Huyện Thường Tín",
    "Xóm 3, Xã Tự Nhiên, Huyện Thường Tín",
    "Thôn Ba Lăng, Xã Dũng Tiến, Huyện Thường Tín",
    "Thôn Nhân Hiền, Xã Hiền Giang, Huyện Thường Tín",
    "Thôn Phương Cù, Xã Thắng Lợi, Huyện Thường Tín",
    "Thôn Quang Trung, Xã Hà Hồi, Huyện Thường Tín",
    "Thôn Vân La, Xã Hồng Vân, Huyện Thường Tín",
    "Phố Quang Trung, Thị trấn Vân Đình, Huyện Ứng Hoà",
    "Thôn Chẩn Kỳ, Xã Trung Tú, Huyện Ứng Hoà",
    "Thôn Đặng Giang, Xã Hoà Phú, Huyện Ứng Hoà",
    "Thôn Đào Xá, Xã Đông Lỗ, Huyện Ứng Hoà",
    "Thôn Đinh Xuyên, Xã Hoà Nam, Huyện Ứng Hoà",
    "Thôn Giang, Xã Viên Nội, Huyện Ứng Hoà",
    "Thôn Hoà Xá ( 1 Thôn ), Xã Hoà Xá, Huyện Ứng Hoà",
    "Thôn Hoàng Dương, Xã Sơn Công, Huyện Ứng Hoà",
    "Thôn Kim Giang, Xã Đại Cường, Huyện Ứng Hoà",
    "Thôn Miêng Thượng, Xã Hoa Sơn, Huyện Ứng Hoà",
    "Thôn Mỹ Cầu, Xã Đồng Tân, Huyện Ứng Hoà",
    "Thôn Nguyễn Xá, Xã Phương Tú, Huyện Ứng Hoà",
    "Thôn Phù Lưu Hạ, Xã Phù Lưu, Huyện Ứng Hoà",
    "Thôn Phù Yên, Xã Viên An, Huyện Ứng Hoà",
    "Thôn Quan Tự, Xã Đại Hùng, Huyện Ứng Hoà",
    "Thôn Quảng Nguyên, Xã Quảng Phù Cầu, Huyện Ứng Hoà",
    "Thôn Tảo Khê, Xã Tảo Dương Văn, Huyện Ứng Hoà",
    "Thôn Thái Bình, Xã Vạn Thái, Huyện Ứng Hoà",
    "Thôn Thanh Bồ, Xã Lưu Hoàng, Huyện Ứng Hoà",
    "Thôn Thành Vật, Xã Đồng Tiến, Huyện Ứng Hoà",
    "Thôn Thu Nội, Xã Trầm Lộng, Huyện Ứng Hoà",
    "Thôn Trạch Bái, Xã Hoà Lâm, Huyện Ứng Hoà",
    "Thôn Triều Khúc, Xã Đội Bình, Huyện Ứng Hoà",
    "Thôn Trung Thịnh, Xã Trường Thịnh, Huyện Ứng Hoà",
    "Thôn Tử Dương, Xã Cao Thành, Huyện Ứng Hoà",
    "Thôn Tu Lễ, Xã Kim Đường, Huyện Ứng Hoà",
    "Thôn Vân Đình, Thị trấn Vân Đình, Huyện Ứng Hoà",
    "Thôn Vũ Ngoại, Xã Liên Bạt, Huyện Ứng Hoà",
    "Thôn Cầu, Xã Minh Đức, Huyện Ứng Hoà"
]

module.exports = addressArray;