const addressArray = [
    "Mumbai G. P. O.",
    "Kalbadevi",
    "Mandvi",
    "Girgaon",
    "Colaba",
    "Malbar Hill",
    "Grant Road",
    "Mumbai Central",
    "Chinch B’der",
    "Mazgaon",
    "Jacob Circle",
    "Parel",
    "Delisle Road",
    "Dadar (C.R.)",
    "Sewree",
    "Mahim",
    "Dharavi",
    "Worli",
    "Matunga",
    "Marine Lines",
    "Nariman Point",
    "Sion",
    "Fort",
    "Nehru Nagar",
    "Prabhadevi",
    "Cumbala Hill",
    "Jijamata Udyan",
    "BS. Rd. Dadar",
    "Airport",
    "Wadala",
    "Mantralaya",
    "Tank Road",
    "Tulsiwadi",
    "Rajbhavan",
    "A. K. Marg",
    "Antop Hill",
    "Ballard pier"
]

module.exports = addressArray;